services:
  jibri-watcher:
    image: alpine
    volumes:
      - openteamskz_jitsi_recordings:/recordings
    command: sh -c "watch -n 5 ls /recordings"

volumes:
  openteamskz_jitsi_recordings:
    external: true